// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaQ308v7GSGyTxUXh6VFLgO3M5Ja6erkw',
    appId: '1:136185653145:web:5444b78e61f20a877c5508',
    messagingSenderId: '136185653145',
    projectId: 'rimzoneshop',
    authDomain: 'rimzoneshop.firebaseapp.com',
    storageBucket: 'rimzoneshop.appspot.com',
    measurementId: "G-84SNX2477K",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPwHGsvb7X6x8pjz01ZfOMWoqP0xWJ5K4',
    appId: '1:136185653145:android:7d929576803b34907c5508',
    messagingSenderId: '136185653145',
    projectId: 'rimzoneshop',
    storageBucket: 'rimzoneshop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGbarR0fl3Qx7QrfQWcbtTRJxOKHP3lV0',
    appId: '1:136185653145:ios:a898359d62a1353a7c5508',
    messagingSenderId: '136185653145',
    projectId: 'rimzoneshop',
    storageBucket: 'rimzoneshop.appspot.com',
    iosBundleId: 'com.example.rimzoneShop',
  );
}
