Map<String, String> arabicTranslation = {
  "Choose": "إختر ",
  "Language": "اللغة",
  "Arabic": "العربية",
  "French": "الفرنسية",
  "English": "الإنكليزية",
  "Continue": "متابعة",
  "onBoardingTitle1": "مظهر جيد, شعور جيد",
  "onBoardingBody1":
      "هل تكره الملابس الموجودة في خزانة ملابسك؟ \n اكتشف المئات من أفكار الملابس",
  "Next": "متابعة",
  "onBoardingTitle2": "ابحث عن ملابسك",
  "onBoardingBody2":
      "هل أنت محتار بشأن ملابسك؟ لا تقلق! \n ابحث عن أفضل الملابس هنا!",
  "onBoardingTitle3": "أناقتك, أسلوبك",
  "onBoardingBody3": "ابتكر أسلوبك الفردي والفريد \n واظهر بمظهر مذهل كل يوم",
  "letsGo": "هيا بنا نبدأ",
  "authPageTitle": "كل ما تحتاجه في مكان واحد",
  "authPageBody":
      "ابحث عن ضرورياتك اليومية في متجر RimZone.  وصلت أكبر تجارة إلكترونية للأزياء في موريتانيا عبر الهاتف المحمول . تسوق الآن!",
  "Login": "تسجيل الدخول ",
  "Register": "تسجيل",
  "loginBody": "قم بتسجيل الدخول لمواصلة استخدام التطبيق",
  "Email": "البريد الإلكتروني",
  "Password": "كلمة المرور",
  "hintText": "أدخل ",
  "Or": "أو",
  "ForgetPassword": "نسيت كلمة المرور",
  "OrLoginWith": "أو عن طريق",
  "loginUnderText": "إنشاء حساب جديد",
  "here!": "من هنا!",
  "signUpUnderText": "لديك حساب ؟ ",
  "Confirm": "تأكيد ",
  "Username": "إسم المستخدم",
  "Check": "تحقق ",
  "The": "من ",
  "ForgetPasswordBody":
      "لا تقلق! هذا يحدث. الرجاء إدخال عنوان البريد الإلكتروني المرتبط بحسابك ليصلك الرمز",
  "Send": "إرسال ",
  "To": "",
  "Code": "الرمز",
  "CodeVerification": "رمز التحقق",
  "OTPVerification": "تحقق من الOTP",
  "VerifyCodeBodySignUp":
      "تم إنشاء حسابك بنجاح,  من أجل الوصول لحسابك, أدخل رمز التحقق الذي أرسل للتو إلى عنوان بريدك الإلكتروني : ",
  "Reset": "إعادة تعيين",
  "NewPassword": "كلمة المرور الجديدة",
  "Save": "حفظ",
  "Create": "إنشاء ",
  "ResetPasswordBody":
      "يجب أن تكون كلمة المرور الجديدة فريدة من نوعها عن تلك المستخدمة سابقًا.",
  "SuccessSignUp": "تم التسجيل بنجاح",
  "Le": "",
  "Phone": "رقم الهاتف",
  "notValid": "عير صالح",
  "SignUpTitle1": "ما هو إسمك ؟",
  "SignUpBody1": "أدخل اسم المستخدم المناسب.",
  "SignUpTitle2": "البريد الإلكتروني ؟",
  "SignUpBody2": "هل ترغب في المصادقة بالبريد الإلكتروني الخاص بك؟",
  "SignUpTitle3": "رقم الهاتف ؟",
  "SignUpBody3": "هل ترغب في المصادقة برقم هاتفك المحمول؟",
  "SignUpTitle4": "الرجاء إدخال كلمة المرور",
  "SignUpBody4":
      "يجب أن تحتوي كلمة المرور على: ثمانية أحرف على الأقل، وحرف كبير واحد على الأقل، وحرف صغير واحد، ورقم واحد، وحرف خاص واحد على الأقل",
  "SignUpTitle5": "تأكيد كلمة المرور",
  "SignUpBody5": "يرجى تأكيد كلمة المرور",
  "isEmpty": "لا يمكن أن يكون فارغ",
  "lessThan": "لا يمن أن يكون أصغر من",
  "greaterThan": "لايمن أن يكون أكبر من",
  "AuthenticateWith": "المصادقة ب",
  "l'": "",
  "This": "هذا",
  "alreadyExists": "موجود بالفعل",
  "ip": "الإتصال بالإنترنت",
  "serverError": "الإتصال بالخادم",
  "serverException": "نحن نعمل على تصحيح هذه الصفحة في أقرب وقت ممكن",
  "Failed": "فشل",
  "stopCreate": "هل تريد التوقف عن إنشاء حسابك؟",
  "ifStopCreate": "إذا توقفت الآن، فسوف تفقد أي تقدم قد أحرزته.",
  "Cancel": "إلغاء",
  "passNotMatch": "غير متطابقة",
  "Error": "خطأ",
  "Warning": "تنبيه",
  "incorrect": "غير صحيح",
  "emailNotFound": "لم يتم العثور على البريد الإلكتروني",
  "willExit": "هل تريد الخروج من التطبيق ؟",
  "Close": "إغلاق",
  "VerifyCodeBodyReset": "أدخل رمز التحقق المرسل عبر البريد الإلكتروني:",
  "isWeak": "ضعيفة",
  "Search": "بحث",
  "successCreateBody": "تم التحقق من الحساب بنجاح. \n يمكنك تسجيل الدخول الآن",
  "successResetBody":
      "تمت إعادة تعيين كلمة المرور بنجاح. \n قم بتسجيل الدخول الآن!",
  "Discover": "إكتشف",
  "Categories": "الأقسام",
  "Offer": "العروض",
  "SeeAll": "الكل",
  "Quantity": "الكمية",
  "addToCart": "أضف إلى السلة",
  "addToFavorite": "تم إضافة المنتج إلى المفضلة",
  "addedToCart": "تم إضافة المنتج إلى السلة",
  "removedFromFavorite": "تم حذف المنتج من المفضلة",
  "couponNotValid": "الرمز الترويجي للخصم غير صالح",
  "cartEmpty": "سلة التسوق الخاصة بك فارغة",
  "onSale": "للبيع",
  "couponName": "الكوبون",
  "myCart": "سلتي",
  "applyPromoCode": "تطبيق",
  "promoCodeApplied": "تم تطبيق الرمز",
  "subTotal": "المجموع الفرعي",
  "deliveryFee": "رسوم التوصيل",
  "discount": "خصم",
  "checkoutFor": "الطلب مقابل",
  "checkout": "إرسال الطلب",
  "terminate": "تم",
  "tryAgain": "أعد المحاولة",
  "pleaseChooseAddress": "الرجاء اختيار العنوان",
  "pleaseChooseDeliveryType": "الرجاء اختيار نوع التسليم",
  "pleaseChoosePaymentMethod": "الرجاء اختيار طريقة الدفع",
  "enterDataAddress": "يجب عليك ملء كافة الحقول",
  "Name": "الإسم",
  "City": "المدينة",
  "Street": "الشارع",
  "Address": "العنوان",
  "Add": "إضافة",
  "emptyAddress": "لم يتم تسجيل أي عنوان",
  //
  "deliveryType": "نوع التوصيل",
  "creditCard": "بطاقة إئتمان",
  "cash": "نقدي",
  "Shipping": "الشحن",
  "Payment": "الدفع",
  "Reviews": "مراجعة",
  "atStore": "استلام عند المتجر",
  "onSpace": "في الحال", // في الحال
  "standardDelivery": "التوصيل المعتاد",
  "delivery": "توصيل",
  "paymentMethod": "طريقة الدفع",
  "cardNumber": "رقم البطاقة",
  "expiration": "انتهاء الصلاحية",
  "securityCode": "رمز الحماية",
  "voucherCode": "رمز القسيمة",
  "sentence":
      "لقد قمت بتعيين عنوان الشحن الخاص بي ليكون بمثابة عنوان إرسال الفواتير الخاص بي أيضًا",
  "Completed": "مكتمل",
  "shipTo": "يشحن إلى",
  "atTheLocationSpecified": "في المكان المحدد",
  "with": "ب",
  "Product": "منتج",
  "youHaveOrdered": "لقد قمت بطلب",
  "productInOrder": "منتج (منتجات)",
  "total": "المجموع",
  "myFavorite": "مفضلتي",
  "inStock": "في المخزون",
  "notInStock": "ليس في المخزون",
  "General": "عام",
  "changePassword": "تغيير كلمة المرور",
  "orders": "طلبات",
  "language": "اللغة",
  "logout": "تسجيل الخروج",
  "Personalization": "إضفاء الطابع الشخصي",
  "Notifications": "إشعارات",
  "Support": "الدعم",
  "About": "حول التطبيق",
  "contactUS": "اتصل بنا",
  "ordersStatus": "حالة الطلب",
  "Pending": "قيد الانتظار",
  "Delivered": "تم التوصيل",
  "Preparing": "قيد التحضير",
  "Rejected": "مرفوض",
  "Details": "تفاصيل",
  "ordersN": "الطلب رقم",
  "Archive": "الأرشيف",
  "pageEmpty": "هذه الصفحة فارقة",
  "ordersDetails": "تفاصيل الطلب",
};
