Map<String, String> englishTranslation = {
  "Choose": "Choose ",
  "Language": "Language",
  "Arabic": "Arabic",
  "French": "French",
  "English": "English",
  "Continue": "Continue",
  "onBoardingTitle1": "Look Good, Food Good",
  "onBoardingBody1":
      "Hating the clothes in your wardrobe ? \n Explore hundreds of outfit ideas",
  "Next": "Next",
  "onBoardingTitle2": "Find Your Outfits",
  "onBoardingBody2":
      "Confused about your outfit? Don't Worry! \n Find the best outfit here!",
  "onBoardingTitle3": "Your Style, Your Way",
  "onBoardingBody3":
      "Create your individual & unique style and \n look amazing everyday",
  "letsGo": "Let's get started",
  "authPageTitle": "Everything you need is in one place",
  "authPageBody":
      "Find your daily necessities at RimZone Shop.\n One of the largest e-commerce sites in Mauritania has arrived on mobile.\n Shop now!",
  "Login": "Login ",
  "Register": "Register",
  "loginBody": "Login to continue using the app",
  "Email": "Email",
  "Password": "Password",
  "hintText": "Enter Your ",
  "Or": "or",
  "ForgetPassword": "Forget password ?",
  "OrLoginWith": "Or login with",
  "loginUnderText": "Create new account",
  "here!": "here!",
  "signUpUnderText": "Already have an account ? ",
  "Confirm": "Confirm ",
  "Username": "Username",
  "Check": "Check ",
  "The": "",
  "ForgetPasswordBody":
      "Don't worry! It occurs. Please enter the email address linked with your account.",
  "Send": "Send ",
  "To": "",
  "CodeVerification": "Verification Code",
  "OTPVerification": "OTP Verification",
  "VerifyCodeBodySignUp":
      "Your account has creating successfully. Know ! For access to your account to your account, enter the verification code we just sent on your email address : ",
  "Reset": "Reset",
  "NewPassword": "New password",
  "Save": "Save",
  "Create": "Create ",
  "ResetPasswordBody":
      "Your new password must be unique from those previously used.",
  "SuccessSignUp": "Success SignUp",
  "Le": "",
  "Phone": "Phone number",
  "notValid": "Not valid",
  "SignUpTitle1": "What is your name ?",
  "SignUpBody1": "Enter the appropriate user name.",
  "SignUpTitle2": "What is your email ?",
  "SignUpBody2": "Would you like to authenticate with your email?",
  "SignUpTitle3": "What is your mobile number?",
  "SignUpBody3": "Would you like to authenticate with your mobile number?",
  "SignUpTitle4": "Please enter a password",
  "SignUpBody4":
      "The password must contain: at least eight characters, at least one uppercase letter, one lowercase letter, one number and at least one special character",
  "SignUpTitle5": "Confirm password",
  "SignUpBody5": "Please confirm the password",
  "isEmpty": "can't be empty",
  "lessThan": "can't be less than",
  "greaterThan": "can't be greater than",
  "AuthenticateWith": "Authenticate with ",
  "l'": "",
  "This": "This",
  "alreadyExists": "already exists",
  "ip": "your internet connection",
  "serverError": "connecting to the server",
  "serverException": "We are working to fix this page as soon as possible",
  "Failed": "Failed",
  "stopCreate": "Do you want to stop creating your account ?",
  "ifStopCreate": "If you stop now, you'll lose any progress you've made.",
  "Cancel": "Cancel",
  "passNotMatch": "does not match",
  "Error": "Error",
  "Warning": "Warning",
  "incorrect": "is incorrect",
  "emailNotFound": "Email is not found",
  "willExit": "Would you exit to app ?",
  "Close": "Close",
  "VerifyCodeBodyReset": "Enter the verification code sent via email : ",
  "isWeak": "is weak",
  "Search": "Search",
  "successCreateBody":
      "Account verification has been completed successfully. \n You can log in now",
  "successResetBody":
      "The password has been reset successfully. \n Log in now!",
  "Discover": "Discover",
  "Categories": "Categories",
  "Offer": "Offers",
  "SeeAll": "All",
  "Quantity": "Quantity",
  "addToCart": "Add to cart",
  "addToFavorite": "The product has been added to favorites",
  "addedToCart": "The product has been added to cart",
  "removedFromFavorite": "The product has been removed from favorites",
  "couponNotValid": "The discount promo code  is invalid",
  "cartEmpty": "Your shopping cart is empty",
  "onSale": "On sale",
  "couponName": "Coupon name",
  "myCart": "My cart",
  "applyPromoCode": "Apply promo code",
  "promoCodeApplied": "Applied",
  "subTotal": "Subtotal",
  "deliveryFee": "Delivery fee",
  "discount": "Discount",
  "checkoutFor": "Order for",
  "checkout": "Submit order",
  "terminate": "Terminated",
  "tryAgain": "Try again",
  "pleaseChooseAddress": "Please Choose Address",
  "pleaseChooseDeliveryType": "Please Choose Delivery Type",
  "pleaseChoosePaymentMethod": "Please Choose Payment Method",
  "enterDataAddress": "You must fill all the fields",
  "Name": "Name",
  "City": "City",
  "Street": "Street",
  "Address": "Address",
  "Add": "Add",
  "emptyAddress": "No address has been registered",
  "deliveryType": "Delivery type",
  "creditCard": "Credit card",
  "cash": "Cash",
  "Shipping": "Shipping",
  "Payment": "Payment",
  "Reviews": "Reviews",
  "atStore": "Pick up at the store",
  "onSpace": "On space", // في الحال
  "standardDelivery": "Standard delivery",
  "delivery": "Delivery",
  "paymentMethod": "Payment method",
  "cardNumber": "Card number",
  "expiration": "Expiration",
  "securityCode": "Security code",
  "voucherCode": "Voucher code",
  "sentence":
      "I have set my shipping address to also serve as my billing address",
  "Completed": "Completed",
  "shipTo": "SHIPPING TO",
  "atTheLocationSpecified": "At the location specified",
  "with": "with",
  "Product": "Product",
  "youHaveOrdered": "You have ordered",
  "productInOrder": "product(s) in this order",
  "total": "Total",
  "myFavorite": "My favorite",
  "inStock": "In stock",
  "notInStock": "Not in stock",
  "General": "General",
  "changePassword": "Change password",
  "orders": "Orders",
  "language": "Language",
  "logout": "Logout",
  "Personalization": "Personalization",
  "Notifications": "Notifications",
  "Support": "Support",
  "About": "About",
  "contactUS": "Contact us",
  "ordersStatus": "Order Status",
  "Pending": "Pending",
  "Delivered": "Delivered",
  "Preparing": "Preparing",
  "Rejected": "Rejected",
  "Details": "Details",
  "ordersN": "Order N",
  "pageEmpty": "This page is empty",
  "Archive": "Archive",
  "ordersDetails": "Order details",
};
