Map<String, String> frenchTranslation = {
  "Choose": "Choisir ",
  "Language": "La Langue",
  "Arabic": "Arab",
  "French": "Français",
  "English": "Anglais",
  "Continue": "Continuer",
  "onBoardingTitle1": "Bien Paraître, Se Sentir Bien",
  "onBoardingBody1":
      "Vous détestez les vêtements de votre garde-robe ? \n explorez des centaines d'idées de tenues",
  "Next": "Continuer",
  "onBoardingTitle2": "Trouvez Vos Tenues",
  "onBoardingBody2":
      "Vous êtes confus au sujet de votre tenue ? \n Ne t'inquiète pas! \n Trouvez la meilleure tenue ici !",
  "onBoardingTitle3": "Votre Style, à Votre Façon",
  "onBoardingBody3":
      "Créez votre style individuel & unique \n Et soyez superbe au quotidien",
  "letsGo": "Démarrer",
  "authPageTitle": "Tout ce dont vous avez besoin est au même endroit",
  "authPageBody":
      "Trouvez vos nécessités quotidiennes chez RimZone Shop.L'un des plus grand e-commerce en Mauritanie est arrivé sur mobile. Achetez maintenant!",
  "Login": "Se Connecter ",
  "Register": "S'inscrire",
  "loginBody": "Connectez-vous pour continuer à utiliser l'application",
  "Email": "Email",
  "Password": "Mot de passe",
  "hintText": "Entrerz Votre ",
  "Or": "ou",
  "ForgetPassword": "Mot de passe oublié ?",
  "OrLoginWith": "Ou à l'aide de",
  "loginUnderText": "Créer un nouveau compte",
  "here!": "ici!",
  "signUpUnderText": "Vous avez un compte ? ",
  "Confirm": "Confirmer ",
  "Username": "Nom d'utilisateur",
  "Check": "Vérifier ",
  "The": "L'",
  "ForgetPasswordBody":
      "Ne t'inquiète pas! Ça arrive. Veuillez saisir l'adresse e-mail liée à votre compte.",
  "Send": "Envoyer ",
  "To": "Le",
  "Code": "Code",
  "CodeVerification": "Code de vérification",
  "OTPVerification": "Verification d'OTP",
  "VerifyCodeBodySignUp":
      "Votre compte a été crée avec succès. Maintenant ! Afin que vous puissiez acceder à votre compte, veuillez saisir le code de vérification que nous venons d'envoyer à votre adresse e-mail : ",
  "Reset": "Réinitialiser",
  "NewPassword": "Nouveau mot de Passe",
  "Save": "Enregistrer",
  "Create": "Créer",
  "ResetPasswordBody":
      "Votre nouveau mot de passe doit être unique par rapport à ceux précédemment utilisés.",
  "SuccessSignUp": "Inscription avec succès",
  "Le": "le",
  "Phone": "Numéro mobile",
  "notValid": "N'est pas valable",
  "SignUpTitle1": "Comment vous appelez-vous ?",
  "SignUpBody1": "Entrez le nom de l'utilisateur approprié.",
  "SignUpTitle2": "Quelle est votre email ?",
  "SignUpBody2": "Voudriez-vous s'authentifier par votre email ?",
  "SignUpTitle3": "Quelle est votre numéro mobile ?",
  "SignUpBody3": "Voudriez-vous s'authentifier avec votre numéro mobile ?",
  "SignUpTitle4": "Veuillez saisir un mot de passe",
  "SignUpBody4":
      "Le mot de passe doit contenir : au moins huit caractères, au moins une lettre majuscule, une lettre minuscule, un chiffre et au moins un caractère spécial",
  "SignUpTitle5": "Confirmer le mot de passe",
  "SignUpBody5": "Veuillez confirmer le mot de passe",
  "isEmpty": "ne peut pas être vide",
  "lessThan": "ne peut pas être inférieur à",
  "greaterThan": "ne peut pas être supérieur à",
  "AuthenticateWith": "S'authentifier avec ",
  "l'": "L'",
  "This": "Ce",
  "alreadyExists": "existe déjà",
  "ip": "votre connexion Interent",
  "serverError": "de connexion au serveur",
  "serverException":
      "Nous travaillons pour corriger cette page dès que possible",
  "Failed": "Échoué",
  "stopCreate": "Voulez-vous arrêter de créer votre compte ?",
  "ifStopCreate":
      "Si vous arrêtez maintenant, vous perdrez tous les progrès que vous avez réalisés.",
  "Cancel": "Annuler",
  "passNotMatch": "ne correspond pas",
  "Error": "Erreur",
  "Warning": "Avertissement",
  "incorrect": "n'est pas correct",
  "emailNotFound": "L'e-mail est introuvable",
  "willExit": "Souhaitez-vous quitter l'application ?",
  "Close": "Fermer",
  "VerifyCodeBodyReset": "Entrez le code de vérification envoyé à l'e-mail :",
  "isWeak": "est faible",
  "Search": "Chercher",
  "successCreateBody":
      "La vérification du compte a été effectuée avec succès. \nVous pouvez vous connecter maintenant",
  "successResetBody":
      "Le mot de passe a été réinitialisé avec succès. \nConnectez-vous maintenant !",
  "Discover": "Découvrir",
  "Categories": "Catégories",
  "Offer": "Offres",
  "SeeAll": "Tout",
  "Quantity": "Quantité",
  "addToCart": "Ajouter au panier",
  "addToFavorite": "Le produit a été ajouté aux favoris",
  "addedToCart": "Le produit a été ajouté au panier",
  "removedFromFavorite": "Le produit a été supprimé des favoris",
  "couponNotValid": "Le code promo de réduction n'est pas valide",
  "cartEmpty": "Votre panier est vide",
  "onSale": "en solde",
  "couponName": "Nom du coupon",
  "myCart": "Mon panier",
  "applyPromoCode": "Appliquer",
  "promoCodeApplied": "Appliquée",
  "subTotal": "Sous-total",
  "deliveryFee": "Frais de livraison",
  "discount": "Réduction",
  "checkoutFor": "Commander pour",
  "checkout": "Soumettre la commande",
  "terminate": "Terminé",
  "tryAgain": "Essayer à nouveau",
  "pleaseChooseAddress": "Veuillez choisir l'adresse",
  "pleaseChooseDeliveryType": "Veuillez choisir le type de livraison",
  "pleaseChoosePaymentMethod": "Veuillez choisir le mode de paiement",
  "enterDataAddress": "Vous devez remplir tous les champs",
  "Name": "Nom",
  "City": "Ville",
  "Street": "Rue",
  "Address": "Addresse",
  "Add": "Ajouter",
  "emptyAddress": "Auccun adresse n'a été enregistré",
  //
  "deliveryType": "Type de livraison",
  "creditCard": "Carte de crédit",
  "cash": "Espèces",
  "Shipping": "Expédition",
  "Payment": "Paiement",
  "Reviews": "Revue",
  "atStore": "Retrait au magasin",
  "onSpace": "Sur espace", // في الحال
  "standardDelivery": "Livraison Standard",
  "delivery": "Livraison",
  "paymentMethod": "Mode de paiement",
  "cardNumber": "Numéro de carte",
  "expiration": "Expiration",
  "securityCode": "Code de sécurité",
  "voucherCode": "Code du bon d'achat",
  "sentence":
      "J'ai défini mon adresse de livraison pour qu'elle serve également d'adresse de facturation",
  "Completed": "Complété",
  "shipTo": "EXPÉDITION À",
  "atTheLocationSpecified": "A l'endroit indiqué",
  "with": "avec",
  "Product": "Produit",
  "youHaveOrdered": "Vous avez commandé",
  "productInOrder": "produit(s) dans cette commande",
  "total": "Total",
  "myFavorite": "Mon préféré",
  "inStock": "En stock",
  "notInStock": "N'est pas en stock",
  "General": "Général",
  "changePassword": "Changer le mot de passe",
  "orders": "Les commandes",
  "language": "Langue",
  "logout": "Se déconnecter",
  "Personalization": "Personnalisation",
  "Notifications": "Notifications",
  "Support": "Soutien",
  "About": "À propos de",
  "contactUS": "Contactez-nous",
  "ordersStatus": "Statut de la commande",
  "Pending": "En attente",
  "Delivered": "Livré",
  "Preparing": "En train de préparer",
  "Rejected": "Rejeté",
  "Details": "Détails",
  "ordersN": "Commande N",
  "Archive": "Archive",
  "pageEmpty": "Cette page est vide",
  "ordersDetails": "Détails du commande",
};
